-- Create school_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS `school_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `school_name` varchar(255) NOT NULL DEFAULT 'Greenwood Academy',
  `school_address` text,
  `school_phone` varchar(50),
  `school_email` varchar(255),
  `school_website` varchar(255),
  `school_logo` varchar(255),
  `principal_name` varchar(255),
  `academic_year_start` date,
  `academic_year_end` date,
  `currency` varchar(10) DEFAULT 'GHS',
  `currency_symbol` varchar(10) DEFAULT '₵',
  `timezone` varchar(100) DEFAULT 'Africa/Accra',
  `terms_per_year` int(11) DEFAULT 3,
  `grading_system` enum('percentage','letter','gpa','points') DEFAULT 'percentage',
  `theme_color` varchar(50) DEFAULT 'blue',
  `default_language` varchar(10) DEFAULT 'en',
  `date_format` varchar(20) DEFAULT 'Y-m-d',
  `time_format` varchar(20) DEFAULT 'H:i',
  `sms_gateway` enum('disabled','twilio','nexmo','local') DEFAULT 'disabled',
  `email_notifications` enum('enabled','disabled','admin_only') DEFAULT 'enabled',
  `parent_portal` enum('enabled','disabled','restricted') DEFAULT 'enabled',
  `student_portal` enum('enabled','disabled','restricted') DEFAULT 'enabled',
  `maintenance_mode` enum('enabled','disabled') DEFAULT 'disabled',
  `registration_enabled` enum('enabled','disabled','admin_only') DEFAULT 'enabled',
  `max_file_upload_size` varchar(10) DEFAULT '10MB',
  `session_timeout` int(11) DEFAULT 30,
  `backup_frequency` enum('daily','weekly','monthly','manual') DEFAULT 'weekly',
  `auto_backup` enum('enabled','disabled') DEFAULT 'enabled',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default settings if table is empty
INSERT IGNORE INTO `school_settings` (
  `id`,
  `school_name`,
  `school_address`,
  `school_phone`,
  `school_email`,
  `school_website`,
  `principal_name`,
  `academic_year_start`,
  `academic_year_end`,
  `currency`,
  `timezone`,
  `terms_per_year`,
  `grading_system`,
  `theme_color`,
  `default_language`,
  `date_format`,
  `time_format`,
  `sms_gateway`,
  `email_notifications`,
  `parent_portal`,
  `student_portal`,
  `maintenance_mode`,
  `registration_enabled`,
  `max_file_upload_size`,
  `session_timeout`,
  `backup_frequency`,
  `auto_backup`
) VALUES (
  1,
  'Greenwood Academy',
  '123 Education Street, Learning City, LC 12345',
  '+1 (234) 567-8900',
  'info@greenwoodacademy.edu',
  'https://www.greenwoodacademy.edu',
  'Dr. Jane Smith',
  '2024-09-01',
  '2025-06-30',
  'GHS',
  'Africa/Accra',
  3,
  'percentage',
  'blue',
  'en',
  'Y-m-d',
  'H:i',
  'disabled',
  'enabled',
  'enabled',
  'enabled',
  'disabled',
  'enabled',
  '10MB',
  30,
  'weekly',
  'enabled'
);

-- Add missing columns if they don't exist (for existing installations)
ALTER TABLE `school_settings` 
ADD COLUMN IF NOT EXISTS `school_logo` varchar(255) AFTER `school_website`,
ADD COLUMN IF NOT EXISTS `currency_symbol` varchar(10) DEFAULT '₵' AFTER `currency`,
ADD COLUMN IF NOT EXISTS `time_format` varchar(20) DEFAULT 'H:i' AFTER `date_format`,
ADD COLUMN IF NOT EXISTS `maintenance_mode` enum('enabled','disabled') DEFAULT 'disabled' AFTER `student_portal`,
ADD COLUMN IF NOT EXISTS `registration_enabled` enum('enabled','disabled','admin_only') DEFAULT 'enabled' AFTER `maintenance_mode`,
ADD COLUMN IF NOT EXISTS `max_file_upload_size` varchar(10) DEFAULT '10MB' AFTER `registration_enabled`,
ADD COLUMN IF NOT EXISTS `session_timeout` int(11) DEFAULT 30 AFTER `max_file_upload_size`,
ADD COLUMN IF NOT EXISTS `backup_frequency` enum('daily','weekly','monthly','manual') DEFAULT 'weekly' AFTER `session_timeout`,
ADD COLUMN IF NOT EXISTS `auto_backup` enum('enabled','disabled') DEFAULT 'enabled' AFTER `backup_frequency`;
